config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'home/about'
  root 'home#index'
  devise_for :users, controllers:{registrations: 'users/registrations'}
  resources :movies, param: :slug do
    resources :reviews, except: :show
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end

      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
  <div class="container-fluid">
    <%= link_to 'Movie App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active", aria_current: "page" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More
          </a>
          <ul class="dropdown-menu">
            <li>
              <hr class="dropdown-divider">
            </li>
          </ul>
        </li>
      </ul>

      <% if user_signed_in? %>
        <div class="ms-3">
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        </div>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary ms-3' %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary ms-2' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid" style="margin: 0;">
  <div class="container-fluid p-5">
    <h1 class="display-4 text-center">Movie Review Application</h1>
    <p class="lead text-center">This project is a Ruby on Rails application that allows users to sign in and sign up using a username, manage their movie collections, and post reviews. Users can explore movies, filter them by genre and showing status, and interact with other users through reviews.</p>
    <div class="text-center">
      <img src="<%= asset_path('background.jpg') %>" class="img-fluid" alt="Movies" style="max-width: 100%; height: auto; margin-top: 20px;">
    </div>
    <hr class="my-4">
    <p class="text-center">Get started by browsing our collection of movies!</p>
    <div class="text-center">
      <%= link_to 'Explore Movies', movies_path, class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
</div>